/*
 * Copyright (c) 2015 Samsung Electronics Co., Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.samsung.memoryanalysis.traceparser;

import java.util.List;

import com.samsung.memoryanalysis.traceparser.SourceMap.SourceLocId;

/**
 * Interface for analyses operating on "enhanced trace," generated by the
 * lifetime analysis.
 *
 * Note that in addition to the unreachability method below, an enhanced trace
 * analysis will not receive the endLastUse() callback. Last use and
 * unreachability callbacks are guaranteed to be invoked in propers order with
 * other trace events.
 */
public interface EnhancedTraceAnalysis<T> extends TraceAnalysis<T> {

    public void unreachableObject(SourceLocId slId, List<Integer> objectIds);

}
